= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

include::partial$prerequisites.adoc[]


[#openshift]
== Setup OpenShift 4

:profile: my_profile

include::partial$openshift-setup.adoc[]


ifeval::["{use-quay-io}" == "true"]
[#container-registry-account]
== Container Registry Account

include::partial$create-quay-account.adoc[]

endif::[]

[#which-terminal]
== Which Terminal

Throughout the lab you will have to run commands in a terminal, you can choose to run everything in your computer or in a web-terminal and web-ide. Whichever decision is fine but you have to honor that decision for the whole lab or redo some commands if you change, in this case... you will be on your own.

[CAUTION]
====
*If you choose to use web-terminal, stick to that decision throughout the whole guide.*

Next, *open the following link*, *create a new project* called: `terminal-{username}` and *click on `Start`*. If credentials are required use these:

- *USERNAME:* {username}
- *PASSWORD:* {password}

[.console-input]
[source,bash, subs="+attributes"]
----
https://{openshift-console-host}/terminal
----
====

[#download-tutorial]
== Get tutorial sources

Even though in a following chapter you will need to fork this repository you still need to clone it locally first to bootstrap the environment.

:tutorial-url: https://github.com/atarazana/kitchensink-conf.git
:folder: kitchensink-guides
include::partial$download-sources.adoc[]