= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

include::partial$prerequisites.adoc[]

ifeval::["{use-quay-io}" == "true"]
[#container-registry-account]
== Container Registry Account

include::partial$create-quay-account.adoc[]

endif::[]

[#which-terminal]
== Which Terminal

Throughout the lab you will have to run commands in a terminal, you can choose to run everything in your computer or in a web-terminal and web-ide. Whichever decision is fine but you have to honor that decision for the whole lab or redo some commands if you change, in this case... you will be on your own.

[CAUTION]
====
*If you choose to use web-terminal, stick to that decision throughout the whole guide.*

Next, *open the following link*, *create a new project* called: `terminal-{username}` and *click on `Start`*. If credentials are required use these:

- *USERNAME:* {username}
- *PASSWORD:* {password}

[.console-input]
[source,bash, subs="+attributes"]
----
https://{openshift-console-host}/terminal
----

Once inside type this command to avoid the session being terminated before you have had time to finish the lab. This command could involve restarting the terminal so please run it before actually starting the lab.

[.console-input]
[source,bash,subs="+attributes"]
----
wtoctl set timeout 240m
----

====

[#download-tutorial]
== Get tutorial sources

If you prefer to use #OpenShift Dev Spaces# instead of your laptop (your own shell) or your browser (web-terminal) just go to the xref:03-prepare-devspaces.adoc[next section], otherwise:

:tutorial-url: https://{gitea-host}/{username}/kitchensink.git
:folder: kitchensink-lab
include::partial$download-sources.adoc[]