= CI/CD pipelines to close the circle
include::_attributes.adoc[]

In this chapter you're going to deploy CI and CD pipelines that will help to automate the processes of continuos integration and delivery. It's made of three sections, the first one deploys an ArgoCD Application that will create not only the pipelines but all the necessary elements the other two will guide you to generate the secrets necessary to connect to the git repos and the container image registry.

IMPORTANT: It's a best practice avoid storing secrets in a git repository even if it's private. There are several ways to deal with secrets in this kind of scenarios but in this case we're going to manage them manually for the sake of simplicity.

[#deploying-cicd-pipelines]
== Deploying CICD Pipelines

We are going to deploy another ArgoCD application, this time to deploy pipelines. Please run this command which will create an ApplicationSet to deploy our CICD pipelines.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
cat <<EOF | oc apply -n openshift-gitops -f -
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kitchensink-cicd-{username}
  namespace: openshift-gitops
  labels:
    kitchensink-cicd-appset: "true"
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        ns: "{cicd-namespace}-{username}"
  template:
    metadata:
      name: kitchensink-cicd-{username}
      namespace: openshift-gitops
      labels:
        kitchensink-cicd-app: "true"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: '{{ ns }}'
        name: '{{ cluster }}'
      project: default
      syncPolicy:
        automated:
          selfHeal: true
      source:
        helm:
          parameters:
            - name: kitchensinkRepoUrl
              value: "https://{gitea-host}/{username}/kitchensink"
            - name: kitchensinkRevision
              value: "main"
            - name: kitchensinkConfRepoUrl
              value: "https://{gitea-host}/{username}/kitchensink-conf"
            - name: kitchensinkConfRevision
              value: "main"
            - name: username
              value: "{username}"
            - name: gitSslVerify
              value: "true"
            - name: cicdNamespace
              value: "{cicd-namespace}-{username}"
            - name: overlayDevNamespace
              value: "helm-kustomize-dev-{username}"
            - name: overlayTestNamespace
              value: "helm-kustomize-test-{username}"
            - name: containerRegistryServer
              value: {quay-server}
            - name: containerRegistryOrg
              value: {username}
        path: cicd
        repoURL: "https://{gitea-host}/{username}/kitchensink-conf"
        targetRevision: main
EOF
----

Let's go to ArgoCD console and see how it's going on. Please copy the next link and open it in a new tab.

[.console-input]
[source,bash, subs="+attributes"]
----
https://{argocd-server}/applications?proj=&sync=&health=&namespace=&cluster=&labels=kitchensink-cicd-app
----

And go deeper by clicking on the `Application` object or using the next link.

[.console-input]
[source,bash, subs="+attributes"]
----
https://{argocd-server}/applications/kitchensink-cicd-{username}
----

You can also have a look to the pipelines created in the OpenShift web console.

[.console-input]
[source,bash, subs="+attributes"]
----
https://{openshift-console-host}/dev-pipelines/ns/{cicd-namespace}-{username}
----

[#create-git-secret]
== Create Git Secret

We are going to create secrets instead of storing them in the git repo, but before we do that let’s check that ArgoCD has created the namespace for us.

[NOTE]
====
If the namespace is not there yet, you can check the sync status of the ArgoCD application with: 

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
argocd app list | grep kitchensink-cicd-{username}
----

====

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc get project ${CICD_NAMESPACE}
----

You should see something like this:

[.console-output]
[source,bash, subs="+macros,+attributes"]
----
NAME                 DISPLAY NAME   STATUS
gramola-cicd-user1                  Active
----

Fine, the namespace is in place, *it's time to create the git secret our pipelines will use when cloning and also while creating Pull Requests* which are the fuel for the CD part of the pipelines to promote from one environment to the next.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export GIT_URL="https://{gitea-host}/{username}/kitchensink"
export GIT_USERNAME={username}
export GIT_PAT_SECRET_NAME=$(yq eval '.gitPatSecretName' ./cicd/values.yaml)

cat <<EOF | oc apply -n {cicd-namespace}-{username} -f -
apiVersion: v1
kind: Secret
metadata:
  name: {git-pat-secret-name}
  namespace: {cicd-namespace}-{username}
type: kubernetes.io/basic-auth
stringData:
  user.name: {username}
  user.email: "{username}@example.com"
  username: {username}
  password: ${GIT_PAT}
EOF
----

We need to annotate the secret so that it can actually be used by the pipeline.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc annotate -n {cicd-namespace}-{username} secret {git-pat-secret-name} \
  "tekton.dev/git-0=https://{gitea-host}"
----

[#grant-pull-permissions]
== Granting Pull Permissions

Additionally we have to create the same secret in `dev` and `test` and link it to the default `ServiceAccount` for pulling images from a private registry.

IMPORTANT: If you don't do this the deployment won't be able to run because they lack permissions to pull the image from the private repository.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export CONTAINER_REGISTRY_SECRET_NAME={container-registry-secret-name}

if [ -z "${CONTAINER_REGISTRY_USERNAME}" ] && [ -z "${CONTAINER_REGISTRY_PASSWORD}" ]; then
    echo "You should provide a value for CONTAINER_REGISTRY_USERNAME and CONTAINER_REGISTRY_PASSWORD"
else
oc create -n helm-kustomize-dev-{username} secret docker-registry ${CONTAINER_REGISTRY_SECRET_NAME} \
  --docker-server=https://$CONTAINER_REGISTRY_SERVER \
  --docker-username=$CONTAINER_REGISTRY_USERNAME \
  --docker-password=$CONTAINER_REGISTRY_PASSWORD
oc secrets link default ${CONTAINER_REGISTRY_SECRET_NAME} --for=pull -n helm-kustomize-dev-{username}
oc create -n helm-kustomize-test-{username} secret docker-registry ${CONTAINER_REGISTRY_SECRET_NAME} \
  --docker-server=https://$CONTAINER_REGISTRY_SERVER \
  --docker-username=$CONTAINER_REGISTRY_USERNAME \
  --docker-password=$CONTAINER_REGISTRY_PASSWORD
oc secrets link default ${CONTAINER_REGISTRY_SECRET_NAME} --for=pull -n helm-kustomize-test-{username}
fi
----

CAUTION: *If you have an additional cluster* you *HAVE* to run the following command too.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export ADDITIONAL_API_SERVER_TOKEN=%ADDITIONAL_API_SERVER_TOKEN%
export ADDITIONAL_API_SERVER_MANAGED=api.%ADDITIONAL_BASE_SUBDOMAIN%:6443
oc login --token=${ADDITIONAL_API_SERVER_TOKEN} --server=https://${ADDITIONAL_API_SERVER_MANAGED} --insecure-skip-tls-verify=true

export CONTAINER_REGISTRY_SECRET_NAME=$(yq eval '.containerRegistrySecretName' ./apps/cicd/values.yaml)

if [ -z "${CONTAINER_REGISTRY_USERNAME}" ] && [ -z "${CONTAINER_REGISTRY_PASSWORD}" ]; then
    echo "You should provide a value for CONTAINER_REGISTRY_USERNAME and CONTAINER_REGISTRY_PASSWORD"
else
oc create -n gramola-test-{username} secret docker-registry ${CONTAINER_REGISTRY_SECRET_NAME} \
  --docker-server=https://$CONTAINER_REGISTRY_SERVER \
  --docker-username=$CONTAINER_REGISTRY_USERNAME \
  --docker-password=$CONTAINER_REGISTRY_PASSWORD
oc secrets link default ${CONTAINER_REGISTRY_SECRET_NAME} --for=pull -n gramola-test-{username}
fi

oc login -u {username} -p {password} --server=https://api.{api-domain} --insecure-skip-tls-verify=true
----
